#!/usr/bin/env sh

# do not lint commits to branch 'gh_pages' to enable testing
# GitHub actions locally with nektos/act
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" != "gh_pages" ]; then
  pnpm exec commitlint --edit $1
fi
